spring.application.name=pyapi

spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?user=postgres.dlnvjvomgtxudyafzphn&password=3uUfcnExo52pmskf
spring.datasource.username=postgres
spring.datasource.password=3uUfcnExo52pmskf
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.auto-commit=false
spring.datasource.hikari.maximum-pool-size=5
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

jwt.secret=mysecretkey2026-03-23JuanYMiguel#$%!
jwt.access-expiration-ms=86400000
jwt.refresh-expiration-ms=604800000
jwt.issuer=pyapi