pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build & Test') {
            steps {
                dir('pyapi') {
                    bat '.\\mvnw.cmd clean package'
                }
            }
        }
        
stage('SonarQube Analysis') {
    steps {
        script {
            // Referenciamos el servidor que ya creamos en 'Manage Jenkins > System'
            withSonarQubeEnv('MiServidorSonar') {
                dir('pyapi') {
                    // El comando para Windows usando el wrapper de Maven
                    // Asegúrate de que el projectKey coincida con el que creaste en SonarQube
                    bat '.\\mvnw.cmd sonar:sonar -Dsonar.projectKey=pyapi'
                }
            }
        }
    }
}
        
        stage('Deploy to Tomcat') {
            steps {
                dir('pyapi') {
                    deploy adapters: [tomcat9(credentialsId: 'tomcat-creds', url: 'http://localhost:8081')], 
                           war: 'target/*.war'
                }
            }
        }
    }
}